---
title: "Clustering"
author: "Mansi Tolia"
date: "4/15/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(reshape2)
library(factoextra)
library(purrr)
library(cluster)
library(fmsb)
library(RColorBrewer)
library(data.table)
```

##Performing Clustering
```{r}

df_medians <- read_csv("df_medians.csv")
#Scale dataset:
df_scaled = scale(df_medians)
k = kmeans(df_scaled, centers=7 , nstart=20, iter.max = 25)
#fviz_cluster(k, data=df_scaled)	
table(k$cluster)

df_medians$cluster <- k$cluster
```

##Preparing variables and tables for plotting radar charts
```{r}
###################################################################
#Preparing PCIP for clustering
###################################################################
radar_pcip <- df_medians%>%group_by(cluster) %>%
  summarise(
    pcip03 = mean(pcip05, na.rm = T),
    pcip04 = mean(pcip04, na.rm = T),
    pcip05 = mean(pcip05, na.rm = T),
    pcip09 = mean(pcip09, na.rm = T),
    pcip10 = mean(pcip10, na.rm = T),
    pcip11 = mean(pcip11, na.rm = T),
    pcip12 = mean(pcip12, na.rm = T),
    pcip13 = mean(pcip13, na.rm = T),
    pcip14 = mean(pcip14, na.rm = T),
    pcip15 = mean(pcip15, na.rm = T),
    pcip16 = mean(pcip16, na.rm = T),
    pcip19 = mean(pcip19, na.rm = T),
    pcip22 = mean(pcip22, na.rm = T),
    pcip23 = mean(pcip23, na.rm = T),
    pcip24 = mean(pcip24, na.rm = T),
    pcip25 = mean(pcip25, na.rm = T),
    pcip26 = mean(pcip26, na.rm = T),
    pcip27 = mean(pcip27, na.rm = T),
    pcip29 = mean(pcip29, na.rm = T),
    pcip30 = mean(pcip30, na.rm = T),
    pcip31 = mean(pcip31, na.rm = T),
    pcip38 = mean(pcip38, na.rm = T),
    pcip39 = mean(pcip39, na.rm = T),
    pcip40 = mean(pcip40, na.rm = T),
    pcip41 = mean(pcip41, na.rm = T),
    pcip42 = mean(pcip42, na.rm = T),
    pcip43 = mean(pcip43, na.rm = T),
    pcip44 = mean(pcip44, na.rm = T),
    pcip45 = mean(pcip45, na.rm = T),
    pcip46 = mean(pcip46, na.rm = T),
    pcip47 = mean(pcip47, na.rm = T),
    pcip48 = mean(pcip48, na.rm = T),
    pcip49 = mean(pcip49, na.rm = T),
    pcip50 = mean(pcip50, na.rm = T),
    pcip51 = mean(pcip51, na.rm = T),
    pcip52 = mean(pcip52, na.rm = T),
    pcip54 = mean(pcip54, na.rm = T))

###################################################################
#Preparing ACT Scores for clustering
###################################################################

radar_act <- df_medians%>%group_by(cluster) %>%
  summarise(
    actcm25 = mean(actcm25, na.rm = T),
    actcm75 = mean(actcm75, na.rm = T),
    acten25 = mean(acten25, na.rm = T),
    acten75 = mean(acten75, na.rm = T),
    actmt25 = mean(actmt25, na.rm = T),
    actmt75 = mean(actmt75, na.rm = T))


###################################################################
#Preparing SAT Scores for clustering
###################################################################

radar_sat <- df_medians%>%group_by(cluster) %>%
  summarise(
    satmt25 = mean(satvr25, na.rm = T),
    satmt75 = mean(satvr75, na.rm = T),
    satvr25 = mean(satmt25, na.rm = T),
    satvr75 = mean(satmt75, na.rm = T))

###################################################################
#Preparing Graduation Rates by Race for clustering
###################################################################

radar_gr_race_gender <- df_medians%>%group_by(cluster) %>%
  summarise(
    grrtwh = mean(grrtwh, na.rm = T),
    grrtbk = mean(grrtbk, na.rm = T),
    grrths = mean(grrths, na.rm = T),
    grrtap = mean(grrtap, na.rm = T),
    grrtan = mean(grrtan, na.rm = T),
    grrtun = mean(grrtun, na.rm = T),
    grrtm = mean(grrtm, na.rm = T),
    grrtw = mean(grrtw, na.rm = T))


###################################################################
#Preparing NPT for clustering
###################################################################

radar_npt <- df_medians%>%group_by(cluster) %>%
  summarise(
    npt412 = mean(npt412, na.rm = T),
    npt422 = mean(npt422, na.rm = T),
    npt432 = mean(npt432, na.rm = T),
    npt442 = mean(npt442, na.rm = T),
    npt452 = mean(npt452, na.rm = T),
    npt4_pub = mean(npt4_pub, na.rm = T),
    npt4_priv = mean(npt4_priv, na.rm = T),
    npt41_pub = mean(npt41_pub, na.rm = T),
    npt43_pub = mean(npt43_pub, na.rm = T),
    npt44_pub = mean(npt44_pub, na.rm = T), 
    npt45_pub = mean(npt45_pub, na.rm = T), 
    npt41_priv = mean(npt41_priv, na.rm = T),
    npt42_priv  = mean(npt42_priv, na.rm = T), 
    npt43_priv = mean(npt43_priv, na.rm = T), 
    npt44_priv = mean(npt44_priv, na.rm = T),
    npt45_priv = mean(npt45_priv, na.rm = T))

###################################################################
#Preparing debt and default rates for clustering
###################################################################

radar_debt <- df_medians%>%group_by(cluster) %>%
  summarise(
    debt_mdn = mean(debt_mdn, na.rm = T),
    grad_debt_mdn = mean(grad_debt_mdn, na.rm = T),
    appl_sch_n = mean(appl_sch_n, na.rm = T),
    default = mean(default, na.rm = T),
    loan_a = mean(loan_a, na.rm = T),
    loan_p = mean(loan_p, na.rm = T),
    floan_a = mean(floan_a, na.rm = T),
    floan_p = mean(floan_p, na.rm = T),
    loan_ever = mean(loan_ever, na.rm = T))


###################################################################
#Preparing admission rates for clustering
###################################################################

radar_admissions <- df_medians%>%group_by(cluster) %>%
  summarise(
    dvadm02 = mean(dvadm02, na.rm = T),  
    dvadm03 = mean(dvadm03, na.rm = T),
    dvadm05 = mean(dvadm05, na.rm = T),
    dvadm06 = mean(dvadm06, na.rm = T))
```

```{r}
##Adding clusters to rownames()
rownames(radar_pcip) <- paste("cluster" , letters[1:7] , sep="-")
rownames(radar_act) <- paste("cluster" , letters[1:7] , sep="-")
rownames(radar_sat) <- paste("cluster" , letters[1:7] , sep="-")
rownames(radar_gr_race_gender) <- paste("cluster" , letters[1:7] , sep="-")
rownames(radar_npt) <- paste("cluster" , letters[1:7] , sep="-")
rownames(radar_debt) <- paste("cluster" , letters[1:7] , sep="-")
rownames(radar_admissions) <- paste("cluster" , letters[1:7] , sep="-")

##removing clusters column from tables
radar_pcip <- radar_pcip %>% select(-cluster)
radar_act <- radar_act %>% select(-cluster)
radar_sat <- radar_sat %>% select(-cluster)
radar_gr_race_gender <- radar_gr_race_gender %>% select(-cluster)
radar_npt <- radar_npt %>% select(-cluster)
radar_debt <- radar_debt %>% select(-cluster)
radar_admissions <- radar_admissions %>% select(-cluster)
```

#Radar Chart ased On PCIP
```{r}
colors_border=c( rgb(0.2,0.5,0.5,0.9), 
                 rgb(0.8,0.2,0.5,0.9),  
                 rgb(0.7,0.5,0.1,0.9),
                 rgb(0.2,0,0,0.9),
                 rgb(0,0.9,0,0.9),
                 rgb(0,0.10,0,0.9),
                 rgb(0.5,0.25,0.112,0.9))
colors_in=c( rgb(0.2,0.5,0.5,0.4), 
             rgb(0.8,0.2,0.5,0.4) , 
             rgb(0.7,0.5,0.1,0.4),
             rgb(0.2,0,0,0.2),
             rgb(0,0.9,0,0.2),
             rgb(0,0.10,0,0.2),
             rgb(0.5,0.25,0.112,0.2))

par(xpd = TRUE, mar = c(1, 2, 2,1))
# plot with default options:
radarchart( radar_pcip, axistype=0, 
            maxmin=F,
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            #custom the grid
            cglcol="grey", 
            cglty=1, axislabcol="grey", 
            cglwd=0.8,
            #custom labels
            vlcex=0.8,
            title = "Clustering On PCIP")

# Add a legend
legend(x ="topright",
       legend = rownames(radar_pcip),
       bty = "n", pch=20 , 
       col=colors_in , 
       text.col = "grey", 
       cex=0.8, pt.cex=2)
```

#Radar Chart based on ACT Scores
```{r}
par(xpd = TRUE, mar = c(0.5, 2, 2, 0.5))
radarchart( radar_act, axistype=0 , 
            maxmin=F,
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            #custom the grid
            cglcol="grey", 
            cglty=1, axislabcol="darkgrey", 
            #caxislabels=seq(0,500,100),
            cglwd=0.8,
            calcex = 0.5,
            palcex = 2,
            centerzero = TRUE,
            #custom labels
            vlcex=,
            title = "Clustering on ACT Scores")

# Add a legend
legend(x ="topright",
       legend = rownames(radar_act),
       bty = "n", pch=20 , 
       col=colors_in , 
       text.col = "grey", 
       cex=0.8, pt.cex=2)
```

#Radar Chart based on SAT Scores
```{r}
radarchart( radar_sat, axistype=0 , 
            maxmin=F,
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            #custom the grid
            cglcol="grey", 
            cglty=1, axislabcol="grey", 
            caxislabels=seq(0,500,100),
            cglwd=0.8,
            #custom labels
            vlcex=0.8,
            title = "Clustering on SAT Scores")

# Add a legend
legend(x ="topright",
       legend = rownames(radar_sat),
       bty = "n", pch=20 , 
       col=colors_in , 
       text.col = "grey", 
       cex=0.8, pt.cex=2)
```


#Radar Chart based on Graduation Rates by Race and Gender
```{r}
radarchart( radar_gr_race_gender, axistype=1 , 
            maxmin=F,
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            #custom the grid
            cglcol="grey", 
            cglty=1, axislabcol="grey", 
            caxislabels=seq(0,20,5),
            cglwd=0.8,
            #custom labels
            vlcex=0.8,
            title = "Clustering on Graduatio Rates by Race and Gender")

# Add a legend
legend(x ="topright",
       legend = rownames(radar_gr_race_gender),
       bty = "n", pch=20 , 
       col=colors_in , 
       text.col = "grey", 
       cex=0.8, pt.cex=2)
```


#Radar Chart based on College Price
```{r}
radarchart( radar_npt, axistype=1 , 
            maxmin=F,
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            #custom the grid
            cglcol="grey", 
            cglty=1, axislabcol="grey", 
            caxislabels=seq(0,20,5),
            cglwd=0.8,
            #custom labels
            vlcex=0.8,
            title = "Clustering on College Price")

# Add a legend
legend(x ="topright",
       legend = rownames(radar_npt),
       bty = "n", pch=20 , 
       col=colors_in , 
       text.col = "grey", 
       cex=0.8, pt.cex=2)
```

#Radar Chart based on Debt
```{r}
radarchart( radar_debt, axistype=1 , 
            maxmin=F,
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            #custom the grid
            cglcol="grey", 
            cglty=1, axislabcol="grey", 
            caxislabels=seq(0,20,5),
            cglwd=0.8,
            #custom labels
            vlcex=0.8,
            title = "Clustering on Debt")

# Add a legend
legend(x ="topright",
       legend = rownames(radar_debt),
       bty = "n", pch=20 , 
       col=colors_in , 
       text.col = "grey", 
       cex=0.8, pt.cex=2)
```

#Radar Chart based on Admission Rates
```{r}
radarchart( radar_admissions, axistype=1 , 
            maxmin=F,
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            #custom the grid
            cglcol="grey", 
            cglty=1, axislabcol="grey", 
            caxislabels=seq(0,20,5),
            cglwd=0.8,
            #custom labels
            vlcex=0.8,
            title = "Clustering on Admission Rates")

# Add a legend
legend(x ="topright",
       legend = rownames(radar_admissions),
       bty = "n", pch=20 , 
       col=colors_in , 
       text.col = "grey", 
       cex=0.8, pt.cex=2)
```