---
title: "Net Price"
author: "Lyufan Pan"
date: "February 14, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(data.table)
```

import all data related to net price from '08 to '17
```{r}
## np = net price
np1 <- read_csv("data/net price/0809-0910S.csv")
np2 <- read_csv("data/net price/1011-1314S.csv")
np3 <- read_csv("data/net price/1415-1718S.csv")
```

get one big table
```{r}
np <- left_join(np1, np2, by = c("UnitID", "Institution Name")) %>% 
  left_join(data3, by = c("UnitID", "Institution Name"))

## delete columns with only NA
np <- np[, -which(apply(np, 2, 
                        function(x) all(is.na(x))))]

# write.csv(np, "data/net price/totalNetPrice.csv")
```

reshape the table by year
```{r}
np %>% 
  select(UnitID, contains("412")) %>% 
  gather(year, type1, -"UnitID") ->type1

np %>% 
  select(UnitID, contains("422")) %>% 
  gather(year, type2, -"UnitID") ->type2

np %>% 
  select(UnitID, contains("432")) %>% 
  gather(year, type3, -"UnitID") ->type3

np %>% 
  select(UnitID, contains("442")) %>% 
  gather(year, type4, -"UnitID") ->type4

np %>% 
  select(UnitID, contains("452")) %>% 
  gather(year, type5, -"UnitID") ->type5

new_np <- full_join(type1, type2, by = c("UnitID", "year"), all = T) %>% 
  full_join(type3, by = c("UnitID", "year"), all = T) %>% 
  full_join(type4, by = c("UnitID", "year"), all = T) %>% 
  full_join(type5, by = c("UnitID", "year"), all = T)

new_np$year <- substr(new_np$year, 12, 15)
```

calculate the trend for 10 years
```{r}
new_np[is.na(new_np)] <- 0

new_np %>%
  select(-UnitID) %>% 
  group_by(year) %>% 
  summarize_all(sum) -> total_netprice
total_netprice
```
```{r}
total_netprice %>% 
  gather(type, netprice, -year) -> gather_total

gather_total
```

```{r}
ggplot(gather_total, aes(x = year, y = netprice, group = type, color = type)) +
  geom_point() +
  geom_path() +
  labs(title = "Total Net Price from 2008 to 2018")
```

```{r}
new_np %>%
  select(-UnitID) %>% 
  group_by(year) %>% 
  summarize_all(mean) -> mean_netprice

mean_netprice %>% 
  gather(type, netprice, -year) -> gather_mean

gather_mean
```

```{r}
ggplot(gather_mean, aes(x = year, y = netprice, group = type, color = type)) +
  geom_point() +
  geom_path() +
  labs(title = "Average Net Price from 2008 to 2018")
```

